version: '3'
services:
  quotes-web:
    build: ./quotes-web
    ports:
      - "6000-7100:4000"
    links:
      - quotes-db
  quotes-db:
    build: ./quotes-db 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - quotes-web
      - quotes-db
    ports:
      - "90:80"
